name: hotfix

on:
  push:
    branches:
      - 'hotfix/*'

permissions:
  contents: write
  pull-requests: write

jobs:
  hotfix-deploy-uat:
    runs-on: ubuntu-latest
    environment: UAT
    env:
      GH_TOKEN: ${{ secrets.GH_PAT }}
      SFDX_AUTH_URL_UAT : ${{ secrets.SFDX_AUTH_URL_UAT }}
      SF_USERNAME_UAT: ${{ secrets.SF_USERNAME_UAT }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          check-latest: true

      - name: Check versions
        run: |
          which node
          node --version
          npm --version

      - name: Install SF CLI and jq
        run: |
          npm install --global @salesforce/cli
          sudo apt-get update && sudo apt-get install -y jq

      - name: Decode URL and auth UAT
        run: |
          echo "${{ secrets.SFDX_AUTH_URL_UAT }}" > uatSfdxurl.txt
          sf org login sfdx-url \
              --sfdx-url-file uatSfdxurl.txt \
              --alias UAT_SANDBOX --set-default

      - name: Validate (checkonly)
        run: |
          cd ./SYEIA-Beta
          sf project deploy start --manifest manifest/package.xml \
            --target-org UAT_SANDBOX --test-level RunLocalTests \
            --wait 60 --dry-run --json > deploy-results-uat-check.json
          cat deploy-results-uat-check.json | jq '.status,.result'

      - name: Deploy (UAT)
        run: |
          cd ./SYEIA-Beta
          sf project deploy start --manifest manifest/package.xml \
            --target-org UAT_SANDBOX --test-level RunLocalTests \
            --wait 60 --json > deploy-results-uat.json
          cat deploy-results-uat.json | jq '.status,.result'

      - name: Run tests (UAT)
        run: |
          cd ./SYEIA-Beta
          sfdx force:apex:test:run -u UAT_SANDBOX -l RunLocalTests -w 60 -c --json > test-results.json
          FAILURES=$(jq -r '.result.summary.failing' test-results.json)
          if (( FAILURES > 0 )); then exit 1; fi

      - name: Open back-merge PRs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BR="${GITHUB_REF_NAME}"
          # PR into develop
          gh pr create --base develop --head "$BR" --title "Back-merge $BR into develop" --body "Auto PR from hotfix."
          # PR into release/<current> if exists
          if git ls-remote --heads origin | grep -q "refs/heads/release/"; then
            CUR=$(git ls-remote --heads origin "refs/heads/release/*" | tail -n1 | awk -F'/' '{print $NF}')
            gh pr create --base "release/${CUR}" --head "$BR" --title "Back-merge $BR into release/${CUR}" --body "Auto PR from hotfix."
          fi
